@extends('layouts.app')

@section('title', 'Rekap Saldo Cuti')

@section('content')
@include('admin._alerts')
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h3 class="mb-1">Rekap Saldo Cuti</h3><p class="text-muted mb-0">Pantau saldo cuti per pegawai dan per jenis cuti.</p></div>
    <div class="app-action-group"><a href="{{ route('cuti.balances.pdf', request()->query()) }}" class="app-icon-btn pdf"><i class="fas fa-file-pdf"></i></a><a href="{{ route('cuti.balances.excel', request()->query()) }}" class="app-icon-btn download"><i class="fas fa-file-excel"></i></a></div>
</div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><form method="GET" action="{{ route('cuti.balances.index') }}"><div class="row"><div class="col-md-2 form-group mb-md-0"><input type="number" name="year" class="form-control" value="{{ $filters['year'] ?? now()->year }}" placeholder="Tahun"></div><div class="col-md-3 form-group mb-md-0"><select name="leave_type_id" class="form-control"><option value="">Semua Jenis</option>@foreach($leaveTypes as $leaveType)<option value="{{ $leaveType->id }}" {{ (string) ($filters['leave_type_id'] ?? '') === (string) $leaveType->id ? 'selected' : '' }}>{{ $leaveType->name }}</option>@endforeach</select></div><div class="col-md-3 form-group mb-md-0"><select name="unit_id" class="form-control"><option value="">Semua Unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" {{ (string) ($filters['unit_id'] ?? '') === (string) $unit->id ? 'selected' : '' }}>{{ $unit->nama }}</option>@endforeach</select></div><div class="col-md-2 form-group mb-md-0"><input type="text" name="search" class="form-control" value="{{ $filters['search'] ?? '' }}" placeholder="Nama / NIP"></div><div class="col-md-2 d-flex" style="gap:6px;"><button type="submit" class="btn btn-primary btn-block">Filter</button><a href="{{ route('cuti.balances.index') }}" class="btn btn-outline-secondary">Reset</a></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Pegawai</th><th>Unit</th><th>Jenis Cuti</th><th>Tahun</th><th>Hak</th><th>Terpakai</th><th>Reserved</th><th>Sisa</th></tr></thead><tbody>@forelse($balances as $balance)<tr><td>{{ optional($balance->user)->name }}<br><small class="text-muted">{{ optional($balance->user)->nip ?: '-' }}</small></td><td>{{ optional(optional($balance->user)->unit)->nama ?: '-' }}</td><td>{{ optional($balance->leaveType)->name }}</td><td>{{ $balance->year }}</td><td>{{ $balance->opening_balance + $balance->entitlement + $balance->carry_forward + $balance->adjustment_plus - $balance->adjustment_minus }}</td><td>{{ $balance->used_days }}</td><td>{{ $balance->reserved_days }}</td><td><span class="badge badge-{{ $balance->remaining_balance > 0 ? 'success' : 'secondary' }}">{{ $balance->remaining_balance }}</span></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada data saldo cuti.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer clearfix">{{ $balances->links() }}</div></div>
@endsection
