@extends('layouts.app')

@section('title', 'Laporan Pengajuan Cuti')

@section('content')
@include('admin._alerts')
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h3 class="mb-1">Laporan Pengajuan Cuti</h3><p class="text-muted mb-0">Rekap pengajuan, approval, dan status dokumen final cuti.</p></div>
    <div class="app-action-group">
        <a href="{{ route('cuti.reports.pdf', request()->query()) }}" class="app-icon-btn pdf"><i class="fas fa-file-pdf"></i></a>
        <a href="{{ route('cuti.reports.excel', request()->query()) }}" class="app-icon-btn download"><i class="fas fa-file-excel"></i></a>
    </div>
</div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><form method="GET" action="{{ route('cuti.reports.index') }}"><div class="row"><div class="col-md-2 form-group mb-md-0"><select name="status" class="form-control"><option value="">Semua Status</option>@foreach(['draft'=>'Draft','submitted'=>'Diajukan','under_review'=>'Ditinjau','verified'=>'Terverifikasi','approved'=>'Disetujui','rejected'=>'Ditolak','cancelled'=>'Dibatalkan','completed'=>'Selesai'] as $value => $label)<option value="{{ $value }}" {{ ($filters['status'] ?? '') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div><div class="col-md-2 form-group mb-md-0"><select name="leave_type_id" class="form-control"><option value="">Semua Jenis</option>@foreach($leaveTypes as $leaveType)<option value="{{ $leaveType->id }}" {{ (string) ($filters['leave_type_id'] ?? '') === (string) $leaveType->id ? 'selected' : '' }}>{{ $leaveType->name }}</option>@endforeach</select></div><div class="col-md-2 form-group mb-md-0"><select name="unit_id" class="form-control"><option value="">Semua Unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" {{ (string) ($filters['unit_id'] ?? '') === (string) $unit->id ? 'selected' : '' }}>{{ $unit->nama }}</option>@endforeach</select></div><div class="col-md-2 form-group mb-md-0"><input type="date" name="date_from" class="form-control" value="{{ $filters['date_from'] ?? '' }}"></div><div class="col-md-2 form-group mb-md-0"><input type="date" name="date_to" class="form-control" value="{{ $filters['date_to'] ?? '' }}"></div><div class="col-md-2 form-group mb-md-0"><input type="text" name="search" class="form-control" value="{{ $filters['search'] ?? '' }}" placeholder="Nomor / nama"></div></div><div class="row mt-2"><div class="col-md-12 d-flex justify-content-end" style="gap:6px;"><button type="submit" class="btn btn-primary btn-sm">Filter</button><a href="{{ route('cuti.reports.index') }}" class="btn btn-outline-secondary btn-sm">Reset</a></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Nomor</th><th>Pegawai</th><th>Jenis</th><th>Periode</th><th>Hari</th><th>Status</th><th>Approval</th><th>Dokumen Final</th></tr></thead><tbody>@forelse($leaveRequests as $leaveRequest)<tr><td>{{ $leaveRequest->display_number }}</td><td>{{ optional($leaveRequest->user)->name }}<br><small class="text-muted">{{ optional(optional($leaveRequest->user)->unit)->nama ?: '-' }}</small></td><td>{{ optional($leaveRequest->leaveType)->name }}</td><td>{{ $leaveRequest->period_label }}</td><td>{{ $leaveRequest->requested_days }}</td><td>{!! $leaveRequest->status_badge !!}</td><td><small class="text-muted">{{ $leaveRequest->approvals->where('status','approved')->count() }}/{{ $leaveRequest->approvals->count() }} selesai</small></td><td class="app-action-cell">@if(in_array($leaveRequest->status, ['approved','rejected']))<div class="app-action-group"><a href="{{ route('cuti.surat', $leaveRequest) }}" target="_blank" class="app-icon-btn file"><i class="fas fa-file-alt"></i></a></div>@else - @endif</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada data pengajuan cuti.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer clearfix">{{ $leaveRequests->links() }}</div></div>
@endsection
